on: push
name: deploy theme
jobs:
    web-deploy:
        name: upload theme via ftp
        runs-on: ubuntu-latest
        steps:
            -   name: checkout
                uses: actions/checkout@v3

            -   name: upload
                uses: SamKirkland/FTP-Deploy-Action@4.3.2
                with:
                    server: ${{ secrets.FTP_SERVER }}
                    username: ${{ secrets.FTP_USERNAME }}
                    password: ${{ secrets.FTP_PASSWORD }}
                    local-dir: ./bjj-aachen/
                    server-dir: /web/wp-content/themes/bjj-aachen/

